# -*- coding: utf-8 -*-
"""CHRISTIAN GEOVANY MUNOZ RODRIGUEZ - Ejercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_JyvoT7Ml_ZCpgW5DWWc03nRt_FOFbbW

Nombre: Christian Geovany Muñoz Rodríguez  Código:  221350605

# **Ejercicio 1**
"""

#En una variable guarde una cadena en la cual describa su motivación para estudiar la carrera de computación
motivo= 'Curiosidad por comprender como funciona la tecnología de nuesto día a día'
#imprima en pantalla a la frase completa.
print (motivo)
#Duplique la frase por medio de una operación de repetición e imprima en pantalla.
print (motivo*2)
#Concatene la frase " Gracias por su atención. " al final de su frase e imprima en pantalla.
print (motivo + ", gracias por su atención")
#Aplique al menos tres subdivisiones a su frase e imprima en pantalla.
#1
print (motivo[15])
#2
print (motivo[0:25])
#3
print (motivo[7:])

"""# **Ejercicio 2**"""

#declare dos valores con valores de tipo entero o real
a=45
b=89
#Sume ambas variables e imprima el resultado
print (a+b)
#Reste ambas variables e imprima el resultado
print (a-b)
#Multiplique ambas variables e imprima el resultado
print (a*b)
#Divida ambas variables e imprima el resultado
print (a/b)
#Divida por medio de la división de piso a ambas variables e imprima el resultado
print (b//a)
#Saque el módulo e imprima el resultado
print (b%a)
#Eleve a ambas variables a la potencia 3 e imprima el resultado
print (a**3)
print (b**3)

"""# **Ejercicio 3**"""

#Tome las variables declaradas en el ejercicio 2
a=45
b=89
#Variable 1 igual a Variable 2
print (a==b)
#Variable 1 diferente a Variable 2
print (a!=b)
#Variable 2 mayor que Variable 1
print (b>a)
#Variable 2 menor que Variable 1
print (b<a)
#Variable 1 mayor o igual que Variable 2
print (a>=b)
#Variable 1 menor o igual que Variable 2
print (a<=b)

"""# **Ejercicio 4**"""

#Tome las variables declaradas en el ejercicio 2
a=45
b=89
#no(V1 - 5 >= V2 + 9 y V2 != V1)
print (( not (a-5>=b+9 and b!=a)))
#(V2 x 5 < V1 / 3) o no(V1 == V2 potencia 2)
print ((b*5<a/3) or (not (a==b**2)))

"""# **Indicaciones**

**Ejercicios para verificar los temas de expresiones y variables.**

Realice lo siguiente:

Escribir su nombre y su código en una celda de texto al inicio del documento de google colab.

**Ejercicio 1:** 

Agregue una celda de código y en una variable guarde una cadena en la cual describa su motivación para estudiar la carrera de computación. Hecho esto realice lo siguiente:

*   Imprima en pantalla a la frase completa.
*   Duplique la frase por medio de una operación de repetición e imprima en pantalla.
*   Concatene la frase " Gracias por su atención. " al final de su frase e imprima en pantalla.
*   Aplique al menos tres subdivisiones a su frase e imprima en pantalla.

**Ejercicio 2:**

Declare dos variables (Ej. A = 14 y B = 50.98) con valores de tipo entero o real y realice lo siguiente:

*   Sume ambas variables e imprima el resultado.
*   Reste ambas variables e imprima el resultado.
*   Multiplique ambas variables e imprima el resultado.
*   Divida ambas variables e imprima el resultado.
*   Divida por medio de la división de piso a ambas variables e imprima el resultado.
*   Saque el módulo e imprima el resultado.
*   Eleve a ambas variables a la potencia 3 e imprima el resultado.

**Ejercicio 3:**

Tome las variables declaradas en el ejercicio 2, realice las siguientes comparaciones e imprima el resultado en pantalla:

*   Variable 1 igual a Variable 2
*   Variable 1 diferente a Variable 2
*   Variable 2 mayor que Variable 1
*   Variable 2 menor que Variable 1
*   Variable 1 mayor o igual que Variable 2
*   Variable 1 menor o igual que Variable 2

**Ejercicio 4:**

Tome las variables declaradas en el ejercicio 2 y realice lo siguiente e imprima el resultado en pantalla:



*   **no**(V1 - 5 >= V2 + 9 **y** V2 != V1)
*   (V2 x 5 < V1 / 3) **o** **no**(V1 == V2 potencia 2)

**Nota:** Separe cada ejercicio en una celda de código distinta y agregue una celda de texto que indique el nombre del ejercicio.
"""