# -*- coding: utf-8 -*-
"""CHRISTIAN GEOVANY MUNOZ RODRIGUEZ - Ejercicio4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZ8irqV3EcI7Eh_2CsM2wusltTzNDCAH

# **Sentencia Iterativa While**

**Ejercicio 1**


> Iniciar una variable (contador) con un valor de 50. Imprimir la palabra PROGRAMACIÓN mientras que el valor del contador sea mayor que 12, el contador se ira decrementando de tres en tres.
"""

x= 50
print("Programación x13 ")
while x > 12:
  print("\nProgramación")
  x -= 3
print("\nFin")